### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by Vekhir** [google/ghc-source-gen#104]
Hi,
The current `master` branch supports GHC 9.4, but there was no release to hackage. This effectively blocks Arch Linux from upgrading to newer versions of GHC.

Please make a new release including the support for GHC 9.4.
Are there specific roadblocks preventing a release at this time? I also saw another PR for GHC 9.6 support.

Gratefully,
Vekhir

**Comment by blackgnezdo** [comment]
I can do the pushes, but first I need help (or find the time) to fix the CI and extend it to support 9.4. I don't want to push something which I don't know keeps working as we make more changes.

**Comment by ysangkok** [comment]
@blackgnezdo Is the current CircleCI working and are its results publicly accessible?

**Comment by blackgnezdo** [comment]
We got one now as part of #107.

**Comment by blackgnezdo** [comment]
I mean we got a CI. @jinwoo could you do a release or add me as a co-maintainer on hackage?

**Comment by jinwoo** [comment]
I just uploaded to hackage. Fortunately I still have `stack` on my laptop :)

I don't think I can add other people as co-maintainers. Last time, I emailed to the hackage folks and cc'd Judah. Once Judah confirmed he was okay with me as a co-maintainer, they added me. Maybe you can do the same, @blackgnezdo ?

**Comment by ysangkok** [comment]
@jinwoo Since you are listed as a maintainer yourself, you can add Hackage maintainers from this page, which also lists all current maintainers: https://hackage.haskell.org/package/ghc-source-gen/maintainers/

You will have to put in [gnezdo](https://hackage.haskell.org/user/gnezdo) as the user.

**Comment by jinwoo** [comment]
@ysangkok Good to know. Thanks! @blackgnezdo I added you as a maintainer.

**Comment by Vekhir** [comment]
Also thanks from me! The update works nicely.
