### ISSUE TITLE
where' and let' seem unusable (cannot construct a `RawValBind`?)

### ISSUE THREAD

**Issue by chessai** [google/ghc-source-gen#13]
There seems to be no way with the API provided to construct a `RawValBind`. I discovered this at the same time that I discovered that the docs for `where'` are wrong; patBind does not return a suitable type.

**Comment by judah** [comment]
Thank you for the report!  You're right that the `where'` example is wrong; I'll look into generalizing the type of `patBind` so it can appear there (or in `let'`).

In the meantime you can use `funBind` to construct `RawValBind`.  I'll also look into making that documentation more clear.  See here for an example of generating syntax like `... where q = t`.

**Comment by judah** [comment]
Actual link:
https://github.com/google/ghc-source-gen/blob/a2b101600d206515085757d119415bbe91f4a870/tests/pprint_examples.hs#L54

**Comment by chessai** [comment]
That will work, thanks!

**Comment by judah** [comment]
Resolved by #14, #15 and #18.

**Comment by chessai** [comment]
Thanks!
