### ISSUE TITLE
Expose builtSpan

### ISSUE THREAD

**Issue by isovector** [google/ghc-source-gen#52]
When interoping with `ghc-exactprint`, getting unique source spans is crucial for connecting annotations to everything. I do this today by locating `noSrcSpan`s, and generating unique spans for them. Without `builtSpan` being exposed, this approach doesn't work!

**Comment by judah** [comment]
`builtSpan` is implemented using `mkGeneralSrcSpan`:
http://hackage.haskell.org/package/ghc-8.6.5/docs/SrcLoc.html#v:mkGeneralSrcSpan

Would it be enough for your use case to check for "unhelpful" `SrcSpan`s by looking for those for which `isGoodSrcSpan` returns `False`?  (From the docs, "good" means precisely that it has source information.)  That seems like a more general approach that wouldn't rely on detals of `ghc-source-gen`'s implementation.

**Comment by isovector** [comment]
Yeah, I came to that approach too. Thanks!
