### ISSUE TITLE
Support GHC 9

### ISSUE THREAD

**Issue by mithrandi** [google/ghc-source-gen#77]
I am working on this; slowly.

**Comment by brandon-leapyear** [comment]
@mithrandi Are you still making your way through this? Any ETA when this might be done?

**Comment by mithrandi** [comment]
I got most of the way there; will see if I can finish this week but will also put up a draft PR with my work so far.

**Comment by isovector** [comment]
Hi @mithrandi, any report? This issue is currently a blocker for HLS' support of GHC 9.0. I don't want to step on your toes, but I'd also like to get this tackled sooner than later. Are you interested in putting up your PR and taking commits?

**Comment by mithrandi** [comment]
Gah, sorry! See #86, hope it was worth the wait :blush:

**Comment by AriFordsham** [comment]
Close?

**Comment by brandon-leapyear** [comment]
Will there be a Hackage release with this fix soon?

**Comment by brandon-leapyear** [comment]
@mithrandi

**Comment by mithrandi** [comment]
Unfortunately I have no insight into this question (I'm just a casual contributor, not a maintainer / uploader).

**Comment by brandonchinn178** [comment]
@jinwoo are you in charge of uploading to hackage?

**Comment by jinwoo** [comment]
> @jinwoo are you in charge of uploading to hackage?

I don't think I'm in "charge" but I can do that :)
Let me find some time to do that this week.

**Comment by jinwoo** [comment]
The new version has been uploaded to Hackage as 0.4.2.0.
