### ISSUE TITLE
New hackage version?

### ISSUE THREAD

**Issue by isovector** [google/ghc-source-gen#82]
https://github.com/haskell/haskell-language-server/pull/1697 is waiting for a release of #79. Is there any chance of getting a new hackage release? Thanks!

**Comment by blackgnezdo** [comment]
I believe @judah and @jinwoo should have access permissions to upload to http://hackage.haskell.org/package/ghc-source-gen. Maybe we can make it easier on them by updating the changelog and do whatever housekeeping items are needed for the release?

**Comment by isovector** [comment]
Gentle ping on this. @judah --- any dice?

**Comment by isovector** [comment]
Less gentle ping. I've been blocked on this for three months now.  @jinwoo @judah can we please get this on hackage?

**Comment by jinwoo** [comment]
Sorry for the late response. I'm not actively working with Haskell these days and don't have the dev environment handy right now. Let me find some time this week and see what I can do about this.

**Comment by isovector** [comment]
Thanks so much, greatly appreciated, @jinwoo. If y'all are open to adding a maintainer, I'd be happy to step up.

**Comment by jinwoo** [comment]
I uploaded the new version with 0.4.1.0. Closing.
